spring:
  appliation:
    name: ts-safe-server
    description: ts safe server application
    author: <a href="mailto:hhywangwei@gmail.com">WangWei</a>
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 15MB
      max-request-size: 20MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: non_null
      deserialization:
        FAIL_ON_UNKNOWN_PROPERTIES: false
      time-zone: GMT+8
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: dev
      password: appeme_com
      url: jdbc:mysql://cd-cdb-jll51z7q.sql.tencentcdb.com:63658/ts_safe_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hikari:
        maximum-pool-size: 60
        idle-timeout: 3600000
        max-lifetime: 21600000
        data-source-properties:
          cache-prep-stmts: true
          useServerPrepStmts: true
          prep-stmt-cache-size: 250
          prep-stmt-cache-sql-limit: 2048
  flyway:
    locations: classpath:/db
    enabled: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,application/json